meta_product_name: "My Dash"
meta_title: "My Dash - The best way to take care of your vehicles"
meta_description: "All-in-one platform to keep track of all your vehicle's needs."
meta_image: "MDBikeBanner.png" # should exist in `app/assets/images/`
